### ISSUE TITLE
Check on locked rewards

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/filecoin-consensus-pledge-demo#10]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/28468980/225125496-f12c8ac6-550f-49c6-a1af-5a3c2b4c4b70.png">

In picture below.. doesn't the locked rewards depend on the current day. I.e. aren't rewards unlocked at a certain point and should not be included in this value? If we are halfway through, the first half of dict values shouldn't be counted?

**Comment by danlessa** [comment]
@SeanMcOwen this is handled dynamically on the simulation on [`s_sectors_rewards`](https://github.com/BlockScience/filecoin-consensus-pledge-demo/blob/a15dda291aad1348389430d8561d8c9bfdadc623/consensus_pledge_model/logic.py#L357). Locked Rewards which are unlocked are simply "filtered out". They cease to exist on the `AggregateSector` level. This is okay because we do not need to keep track of what the Circulating Supply holders are.

**Comment by SeanMcOwen** [comment]
Ok that works perfect thanks!
