### ISSUE TITLE
Should there be an element of randomness here? Otherwise is it not going to be deterministic?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/filecoin-consensus-pledge-demo#15]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/28468980/225969956-e479aa3c-8ecd-456e-9a55-77e8e949cbe5.png">

Also this is not bound to be between 0-1, is that fine?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/28468980/225970238-18a5556e-30eb-4f23-a5c1-818253b1d07c.png">

**Comment by danlessa** [comment]
Was changed on the commit bc511d580caa25c05b1498a8fe3a4ac7761e56f5 to assume `delta_days` independent trials with probability `daily_renewal_probability` for each `AggregateSector`. 

Being deterministic for the Edu Calculator is a feature. We don't sample because we're using the expected values which is justified given the relatively small sizes of the sectors (32GiB) compared to the typical units being used (1 PiB) and the long horizons (weekly timesteps rather than epochs)
